/**
 * GENERATED by scripts/write-image-sizes.mjs — do not edit by hand.
 *
 * Intrinsic dimensions for portfolio images. The gallery lays tiles out as a
 * masonry, so each image needs its real aspect ratio to reserve the right space
 * before it loads.
 */

export type ImageSize = { w: number; h: number };

export const imageSizes: Record<string, ImageSize> = {
  "/ambiance/archiVerriere.jpg": { w: 2000, h: 1333 },
  "/ambiance/atelierDessin.jpg": { w: 2000, h: 1335 },
  "/ambiance/chambreChaude.jpg": { w: 2000, h: 1125 },
  "/ambiance/heroSalon.jpg": { w: 2000, h: 1500 },
  "/ambiance/linTerracotta.jpg": { w: 2000, h: 3000 },
  "/ambiance/salonBois.jpg": { w: 2000, h: 1360 },
  "/ambiance/salonEditorial.jpg": { w: 2000, h: 1125 },
  "/ambiance/salonPoutres.jpg": { w: 2000, h: 2667 },
  "/ambiance/sejourBois.jpg": { w: 2000, h: 1055 },
  "/DIS%20STUDIO/3DS%20MAX/Camion%20en%203D/1.f.jpg": { w: 1920, h: 1080 },
  "/DIS%20STUDIO/3DS%20MAX/Camion%20en%203D/6.f.jpg": { w: 1920, h: 1080 },
  "/DIS%20STUDIO/3DS%20MAX/Camion%20en%203D/7f.jpg": { w: 1920, h: 1080 },
  "/DIS%20STUDIO/3DS%20MAX/Camion%20en%203D/8f.jpg": { w: 1920, h: 1080 },
  "/DIS%20STUDIO/3DS%20MAX/Camion%20en%203D/f.f.jpg": { w: 1920, h: 1080 },
  "/DIS%20STUDIO/3DS%20MAX/Yacht%20en%203D/1.jpg": { w: 800, h: 517 },
  "/DIS%20STUDIO/3DS%20MAX/Yacht%20en%203D/2.jpg": { w: 800, h: 517 },
  "/DIS%20STUDIO/3DS%20MAX/Yacht%20en%203D/3.jpg": { w: 800, h: 517 },
  "/DIS%20STUDIO/3DS%20MAX/Yacht%20en%203D/6.jpg": { w: 800, h: 517 },
  "/DIS%20STUDIO/3DS%20MAX/Yacht%20en%203D/7.jpg": { w: 800, h: 565 },
  "/DIS%20STUDIO/3DS%20MAX/Yacht%20en%203D/8.jpg": { w: 800, h: 565 },
  "/projets/dossier-chambre/01.jpg": { w: 1920, h: 1358 },
  "/projets/dossier-cuisine/01.jpg": { w: 1920, h: 1358 },
  "/projets/dossier-dressing/01.jpg": { w: 1920, h: 1358 },
  "/projets/dossier-sdb/01.jpg": { w: 1920, h: 1358 },
  "/projets/maison-de-culture/01.jpg": { w: 1920, h: 699 },
  "/projets/maison-de-culture/02.jpg": { w: 1920, h: 519 },
  "/projets/maison-de-culture/03.jpg": { w: 1920, h: 416 },
  "/projets/mareli/01.jpg": { w: 1920, h: 2081 },
  "/projets/mareli/02.jpg": { w: 1453, h: 1534 },
  "/projets/plans-habitation/01.jpg": { w: 1528, h: 2198 },
  "/projets/plans-habitation/02.jpg": { w: 1414, h: 1883 },
  "/projets/plans-habitation/03.jpg": { w: 1632, h: 2536 },
  "/projets/showroom-jeremy/01.jpg": { w: 1920, h: 1861 },
  "/projets/showroom-jeremy/02.jpg": { w: 1920, h: 1326 },
  "/projets/showroom-jeremy/03.jpg": { w: 1920, h: 2238 },
  "/projets/showroom-jeremy/04.jpg": { w: 1920, h: 1489 },
  "/projets/showroom-siceram/01.jpg": { w: 1920, h: 1080 },
  "/projets/showroom-siceram/02.jpg": { w: 1920, h: 1080 },
  "/projets/villa-contemporaine/01.jpg": { w: 1600, h: 947 },
  "/projets/villa-contemporaine/02.jpg": { w: 1397, h: 1080 },
  "/projets/villa-contemporaine/03.jpg": { w: 1600, h: 1027 },
  "/projets/villa-contemporaine/04.jpg": { w: 1600, h: 897 },
  "/projets/villa-contemporaine/05.jpg": { w: 1440, h: 1080 },
  "/projets/villa-contemporaine/06.jpg": { w: 1600, h: 900 },
  "/projets/villa-neoclassique/01.jpg": { w: 1280, h: 837 },
  "/projets/villa-neoclassique/02.jpg": { w: 903, h: 590 },
  "/projets/villa-neoclassique/03.jpg": { w: 1600, h: 975 },
  "/projets/villa-neoclassique/04.jpg": { w: 1600, h: 959 },
  "/projets/villa-wabi-sabi/01.jpg": { w: 1280, h: 1100 },
  "/projets/villa-wabi-sabi/02.jpg": { w: 1440, h: 900 },
  "/projets/villa-wabi-sabi/03.jpg": { w: 1280, h: 809 },
};

/** Falls back to 3:2 for anything not in the map. */
export function sizeOf(src: string): ImageSize {
  return imageSizes[src] ?? { w: 1500, h: 1000 };
}
